### ISSUE TITLE
Create a translation layer server->machine controller

### ISSUE THREAD

**Issue by gareth-smyth** [gareth-smyth/achiir6500#28]
### Acceptance Criteria
- Translation layer receives command objects and converts them into a list of serial commands
  - [ ] Send program returns a list of commands to push each part of the program to the machine controller
  - [ ] Start program returns a single command to start the program
  - [ ] Get current value (i.e. the current temp for a running program) returns a (single?) command to get the current value
- Response also includes a call back to handle the response
  - [ ] Send program callback when all commands are successful returns program run object
  - [ ] Send program returns throws an exception when any command fails
  - [ ] Start program callback returns success/failure based on response
  - [ ] Get current value callback returns a ProgramRunValue which is program_run_id, date_time?, value
